image:
  name: atlassian/pipelines-awscli

definitions:
  steps:
    - step: &build-and-push-bakend
        name: build and push docker image
        caches:
          - docker
        services:
          - docker
        script:
          # build the Docker image 
          - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
          # aws login
          - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
          - docker build -f ./services/backend/Dockerfile -t ${AWS_REGISTRY_URL}:$BUILD_ID .
          - docker push ${AWS_REGISTRY_URL}:$BUILD_ID
          - docker tag ${AWS_REGISTRY_URL}:$BUILD_ID ${AWS_REGISTRY_URL}:$BITBUCKET_BRANCH
          - docker push ${AWS_REGISTRY_URL}:$BITBUCKET_BRANCH

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."

  branches:
    develop:
      - step: *build-and-push-bakend
    master:
      - step: *build-and-push-bakend