image:
  name: atlassian/pipelines-awscli
definitions:
  caches:
    nodecustom: ./node_modules
    yarn: /usr/local/share/.cache/yarn
  steps:
    - step: &Test-step
        image: node:lts
        name: 'Testing...'
        caches:
          - nodecustom
          - yarn
        script:
            - yarn install --frozen-lockfile
            - yarn test
    - step: &Lint-step
        image: node:lts
        name: 'Linting...'
        caches:
          - nodecustom
          - yarn
        script:
            - yarn install --frozen-lockfile
            - yarn lint
    - step: &build-and-push-bakend
        name: build and push docker image
        caches:
          - docker
        services:
          - docker
        script:
          - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
          - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
          - docker build -f ./services/backend/Dockerfile -t ${AWS_REGISTRY_URL}:backend-$BUILD_ID .
          - docker push ${AWS_REGISTRY_URL}:backend-$BUILD_ID
          - docker tag ${AWS_REGISTRY_URL}:backend-$BUILD_ID ${AWS_REGISTRY_URL}:backend-$BITBUCKET_BRANCH
          - docker push ${AWS_REGISTRY_URL}:backend-$BITBUCKET_BRANCH
pipelines:
  branches:
    develop:
      - parallel:
        - step: *Test-step
        - step: *Lint-step
      - step: *build-and-push-bakend
    master:
      - step: *build-and-push-bakend

