image:
  name: atlassian/pipelines-awscli

definitions:
  steps:
    - step: &Build-and-Test
        name: 'Build and Test'
        script:
          - echo "Your build and test goes here..."
    - step: &Lint
        name: 'Lint'
        script:
          - echo "Your linting goes here..."
    - step: &build-and-push-bakend
        name: build and push docker image
        caches:
          - docker
        services:
          - docker
        script:
          - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
          - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
          - docker build -f ./services/backend/Dockerfile -t ${AWS_REGISTRY_URL}:backend-$BUILD_ID .
          - docker push ${AWS_REGISTRY_URL}:backend-$BUILD_ID
          - docker tag ${AWS_REGISTRY_URL}:backend-$BUILD_ID ${AWS_REGISTRY_URL}:backend-$BITBUCKET_BRANCH
          - docker push ${AWS_REGISTRY_URL}:backend-$BITBUCKET_BRANCH
pipelines:
  branches:
    develop:
      - parallel:
        - step: *Build-and-Test
        - step: *Lint
      - step: *build-and-push-bakend
    master:
      - step: *build-and-push-bakend

