version: '3.8'

services: 
  mongo:
    image: mongo:4.4

  redis:
    image: redis:alpine

  backend:
    build: 
      dockerfile: services/backend/Dockerfile
      context: .
    image: freelance/labs-starter-ecs-backend:${VERSION:-latest}
    environment: 
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'labs-starter-ecs'
    ports:
      - 8000:8000
    depends_on:
      - mongo